name: Build and Deploy Node.js app to Azure Web App - appFront2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3675C1E8CB9A46D295900E7C85047360 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B1FDFB8AAAEF4EBEA537F418DDB5A803 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5CC47D502024455C91D651010AF23942 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appFront2'
          slot-name: 'Production'
          package: .
